"""
Beginner financial analysis project.

This program:
1. Pulls SEC financial statements with EdgarTools.
2. Uses pandas to organize the numbers into clean tables.
3. Uses Beautiful Soup as a helper for future SEC filing text extraction.
4. Uses matplotlib to save chart image files.
5. Uses openpyxl to create a readable Excel workbook with charts.

Each company gets its own folder inside the outputs folder.
"""

import os
import sys

# Keep EdgarTools and matplotlib files inside this project folder.
# This makes the project easier to move, find, and run from IDLE.
os.environ.setdefault("MPLCONFIGDIR", os.path.join(os.getcwd(), ".matplotlib_cache"))
os.environ.setdefault("EDGAR_LOCAL_DATA_DIR", os.path.join(os.getcwd(), ".edgar_data"))
os.environ.setdefault("EDGAR_CACHE_DIR", os.path.join(os.getcwd(), ".edgar_cache"))

from bs4 import BeautifulSoup
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from edgar import Company, set_identity
from openpyxl import load_workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


METRIC_LABELS = {
    "revenue": ["Revenue", "Total Revenue", "Net Sales", "Sales Revenue Net"],
    "net_income": ["Net Income", "Net Income Loss"],
    "income_tax": ["Income Tax Expense Benefit", "Income Tax Expense", "Provision For Income Taxes"],
    "total_assets": ["Total Assets", "Assets"],
    "total_liabilities": ["Total Liabilities", "Liabilities"],
    "total_equity": [
        "Total Stockholders' Equity",
        "Stockholders' Equity",
        "Shareholders' Equity",
        "Total Shareholders' Equity",
        "Total Shareholders’ Equity",
    ],
    "cash_from_operations": [
        "Net Cash Provided by Operating Activities",
        "Net Cash Provided by Used in Operating Activities",
        "Cash Generated by Operating Activities",
    ],
    "capital_expenditures": [
        "Payments to Acquire Property Plant and Equipment",
        "Payments for Acquisition of Property, Plant and Equipment",
        "Capital Expenditures",
    ],
}


EXPLANATIONS = [
    {
        "Topic": "Income Statement",
        "Explanation": "Shows revenue, expenses, taxes, and profit over a period of time.",
    },
    {
        "Topic": "Revenue",
        "Explanation": "Money the company earned from selling products or services.",
    },
    {
        "Topic": "Net Income",
        "Explanation": "Profit left after expenses, interest, taxes, and other items.",
    },
    {
        "Topic": "Profit Margin",
        "Explanation": "Net income divided by revenue. It shows how much profit the company keeps from each dollar of sales.",
    },
    {
        "Topic": "Balance Sheet",
        "Explanation": "Shows what the company owns and owes at a specific date.",
    },
    {
        "Topic": "Assets",
        "Explanation": "Resources the company owns, such as cash, receivables, inventory, and equipment.",
    },
    {
        "Topic": "Liabilities",
        "Explanation": "Amounts the company owes, such as accounts payable, debt, and other obligations.",
    },
    {
        "Topic": "Cash Flow Statement",
        "Explanation": "Shows how cash moved through operating, investing, and financing activities.",
    },
    {
        "Topic": "Other Income Negative",
        "Explanation": "A negative other income number usually means non-core expenses were larger than non-core income, such as interest expense, investment losses, foreign exchange losses, or one-time charges.",
    },
]


def make_output_easy_to_read():
    """Make pandas print smaller tables that are easier to read in IDLE."""
    pd.set_option("display.max_columns", 8)
    pd.set_option("display.width", 100)
    pd.set_option("display.max_colwidth", 40)
    pd.set_option("display.float_format", "{:,.2f}".format)


def setup_edgar_identity():
    """Tell the SEC who is making requests."""
    identity = os.getenv("EDGAR_IDENTITY")

    if not identity:
        print("\n--- SEC Identity ---")
        print("The SEC asks programs to identify who is making requests.")
        print("Enter your name and email, like: Jane Doe jane@example.com")
        identity = input("SEC identity: ").strip()

    if not identity:
        print("No identity was entered, so I will use a placeholder for now.")
        identity = "Beginner Python Project example@example.com"

    set_identity(identity)


def ask_for_number_of_periods():
    """Ask how many recent reporting periods the user wants to analyze."""
    print("\n--- Time Period Selection ---")
    print("This program can pull up to 3 recent annual reporting periods.")
    print("Example: enter 3 to see the 3 most recent annual reporting periods.")
    print("Note: some statements may have fewer periods available than you request.")
    answer = input("How many recent reporting periods do you want to analyze? Max is 3: ")

    try:
        number_of_periods = int(answer)
    except ValueError:
        print("That was not a number, so I will use 3 periods.")
        number_of_periods = 3

    if number_of_periods <= 0:
        print("That number was too small, so I will use 3 periods.")
        number_of_periods = 3

    if number_of_periods > 3:
        print("The maximum is 3 periods, so I will use 3.")
        number_of_periods = 3

    return number_of_periods


def extract_text_from_html(html):
    """
    Beautiful Soup helper for future filing text extraction.

    EdgarTools is better for financial statement numbers, but Beautiful Soup can
    help later if you want to pull text from SEC filing HTML.
    """
    soup = BeautifulSoup(html, "html.parser")
    return soup.get_text(separator=" ", strip=True)


def statement_to_dataframe(statement):
    """Convert an EdgarTools statement object into a pandas DataFrame."""
    if hasattr(statement, "to_dataframe"):
        return statement.to_dataframe()

    return pd.DataFrame(statement)


def get_financial_statement_data(ticker):
    """Pull income statement, balance sheet, and cash flow statement."""
    company = Company(ticker)
    financials = company.get_financials()

    return {
        "income_statement": statement_to_dataframe(financials.income_statement(view="summary")),
        "balance_sheet": statement_to_dataframe(financials.balance_sheet(view="summary")),
        "cash_flow_statement": statement_to_dataframe(financials.cashflow_statement(view="summary")),
    }


def get_period_columns(dataframe, number_of_periods=None):
    """Find financial date columns, like 2025-09-27."""
    period_columns = [column for column in dataframe.columns if str(column)[:4].isdigit()]

    # EdgarTools usually returns newest periods first.
    if number_of_periods:
        period_columns = period_columns[:number_of_periods]

    return period_columns


def clean_number(value):
    """Convert SEC values into regular numbers when possible."""
    if pd.isna(value):
        return None

    if isinstance(value, (int, float)):
        return value

    text = str(value).replace("$", "").replace(",", "").strip()
    if text.startswith("(") and text.endswith(")"):
        text = "-" + text[1:-1]

    try:
        return float(text)
    except ValueError:
        return None


def clean_statement_for_excel(dataframe, number_of_periods):
    """Create a clean Excel-style statement table."""
    period_columns = get_period_columns(dataframe, number_of_periods)
    useful_columns = ["label"] + period_columns
    useful_columns = [column for column in useful_columns if column in dataframe.columns]

    clean_df = dataframe[useful_columns].copy()
    clean_df = clean_df.rename(columns={"label": "Line Item"})

    for column in period_columns:
        clean_df[column] = clean_df[column].apply(clean_number)

    return clean_df


def find_row_by_label(dataframe, possible_labels):
    """Find a financial statement row by looking in the label column."""
    if "label" not in dataframe.columns:
        return None

    labels = dataframe["label"].astype(str).str.lower()

    for possible_label in possible_labels:
        exact_matches = dataframe[labels == possible_label.lower()]
        if not exact_matches.empty:
            return exact_matches.iloc[0]

    for possible_label in possible_labels:
        partial_matches = dataframe[labels.str.contains(possible_label.lower(), regex=False)]
        if not partial_matches.empty:
            return partial_matches.iloc[0]

    return None


def row_to_series(row, metric_name, allowed_periods):
    """Convert one financial statement row into a pandas Series by period."""
    if row is None:
        return pd.Series(dtype="float64", name=metric_name)

    allowed_periods = [str(period) for period in allowed_periods]
    values = {}

    for column_name, value in row.items():
        if str(column_name) in allowed_periods:
            number = clean_number(value)
            if number is not None:
                values[str(column_name)] = number

    return pd.Series(values, name=metric_name)


def build_metrics_table(statements, number_of_periods):
    """Build one table with the main metrics to track over time."""
    income_df = statements["income_statement"]
    balance_df = statements["balance_sheet"]
    cash_flow_df = statements["cash_flow_statement"]
    allowed_periods = get_period_columns(income_df, number_of_periods)

    metric_sources = {
        "Revenue": (income_df, METRIC_LABELS["revenue"]),
        "Net Income": (income_df, METRIC_LABELS["net_income"]),
        "Income Tax Expense": (income_df, METRIC_LABELS["income_tax"]),
        "Total Assets": (balance_df, METRIC_LABELS["total_assets"]),
        "Total Liabilities": (balance_df, METRIC_LABELS["total_liabilities"]),
        "Total Equity": (balance_df, METRIC_LABELS["total_equity"]),
        "Cash From Operations": (cash_flow_df, METRIC_LABELS["cash_from_operations"]),
        "Capital Expenditures": (cash_flow_df, METRIC_LABELS["capital_expenditures"]),
    }

    rows = []
    for metric_name, (dataframe, possible_labels) in metric_sources.items():
        row = find_row_by_label(dataframe, possible_labels)
        rows.append(row_to_series(row, metric_name, allowed_periods))

    metrics_df = pd.DataFrame(rows)

    if "Revenue" in metrics_df.index and "Net Income" in metrics_df.index:
        metrics_df.loc["Profit Margin"] = (
            metrics_df.loc["Net Income"] / metrics_df.loc["Revenue"]
        ) * 100

    if "Total Liabilities" in metrics_df.index and "Total Equity" in metrics_df.index:
        metrics_df.loc["Debt To Equity"] = (
            metrics_df.loc["Total Liabilities"] / metrics_df.loc["Total Equity"]
        )

    metrics_df = metrics_df.reindex(sorted(metrics_df.columns), axis=1)
    metrics_df.index.name = "Metric"
    return metrics_df


def build_period_summary_table(statements, requested_periods):
    """Show what periods were requested and what periods were available."""
    rows = []

    for name, dataframe in statements.items():
        all_periods = get_period_columns(dataframe)
        selected_periods = get_period_columns(dataframe, requested_periods)

        rows.append(
            {
                "Statement": name.replace("_", " ").title(),
                "Requested Periods": requested_periods,
                "Available Periods": len(all_periods),
                "Selected Periods": ", ".join(str(period) for period in selected_periods),
                "Note": (
                    "Fewer periods were available than requested."
                    if len(selected_periods) < requested_periods
                    else "Requested periods were available."
                ),
            }
        )

    return pd.DataFrame(rows)


def explain_period_limits(period_summary_df):
    """Explain when EdgarTools returned fewer periods than the user requested."""
    limited_rows = period_summary_df[
        period_summary_df["Available Periods"] < period_summary_df["Requested Periods"]
    ]

    if limited_rows.empty:
        print("\nThe requested number of periods was available for each statement.")
        return

    print("\n--- Period Availability Explanation ---")
    print("The program could not show every period you requested for every statement.")
    print("That usually happens because the SEC filing only includes a limited")
    print("number of comparable periods for that statement.")
    print("For example, balance sheets often show fewer dates than income statements.")

    for _, row in limited_rows.iterrows():
        print(
            f"- {row['Statement']}: you asked for {row['Requested Periods']}, "
            f"but only {row['Available Periods']} were available."
        )


def build_explanations_table():
    """Create a beginner-friendly explanation table."""
    return pd.DataFrame(EXPLANATIONS)


def build_file_map_table(ticker, output_folder):
    """Explain where the program saves each output file."""
    return pd.DataFrame(
        [
            {
                "Item": "Company output folder",
                "Path": os.path.abspath(output_folder),
                "Purpose": "Main folder for this ticker's analysis files.",
            },
            {
                "Item": "Excel workbook",
                "Path": os.path.abspath(os.path.join(output_folder, f"{ticker.lower()}_financial_analysis.xlsx")),
                "Purpose": "Main Excel file with clean tables, explanations, periods, and charts.",
            },
            {
                "Item": "Metrics CSV",
                "Path": os.path.abspath(os.path.join(output_folder, "metrics.csv")),
                "Purpose": "Simple spreadsheet file with the main tracked metrics.",
            },
            {
                "Item": "Charts folder",
                "Path": os.path.abspath(os.path.join(output_folder, "charts")),
                "Purpose": "Folder containing matplotlib chart images.",
            },
        ]
    )


def print_clean_preview(statement_name, clean_dataframe):
    """Print a neat preview that is readable in IDLE."""
    print(f"\n--- {statement_name.replace('_', ' ').title()} ---")
    print(clean_dataframe.head(10).to_string(index=False, na_rep=""))


def create_company_output_folder(ticker):
    """Create one folder for this ticker's files and charts."""
    output_folder = os.path.join("outputs", ticker.upper())
    os.makedirs(output_folder, exist_ok=True)
    os.makedirs(os.path.join(output_folder, "charts"), exist_ok=True)
    return output_folder


def format_excel_sheet(worksheet):
    """Make a worksheet easier to read."""
    header_fill = PatternFill("solid", fgColor="D9EAF7")

    for cell in worksheet[1]:
        cell.font = Font(bold=True)
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")

    worksheet.freeze_panes = "A2"

    for column_cells in worksheet.columns:
        column_letter = get_column_letter(column_cells[0].column)
        max_length = 12

        for cell in column_cells:
            if cell.value is not None:
                max_length = max(max_length, len(str(cell.value)) + 2)

        worksheet.column_dimensions[column_letter].width = min(max_length, 45)


def add_excel_line_chart(workbook, metric_name, title, anchor):
    """Add one Excel line chart using the metrics sheet."""
    metrics_sheet = workbook["metrics"]
    chart_sheet = workbook["excel_charts"]

    metric_row = None
    for row_number in range(2, metrics_sheet.max_row + 1):
        if metrics_sheet.cell(row=row_number, column=1).value == metric_name:
            metric_row = row_number
            break

    if metric_row is None:
        return

    chart = LineChart()
    chart.title = title
    chart.y_axis.title = metric_name
    chart.x_axis.title = "Reporting Period"

    data = Reference(
        metrics_sheet,
        min_col=2,
        max_col=metrics_sheet.max_column,
        min_row=metric_row,
        max_row=metric_row,
    )
    categories = Reference(
        metrics_sheet,
        min_col=2,
        max_col=metrics_sheet.max_column,
        min_row=1,
        max_row=1,
    )

    chart.add_data(data, from_rows=True, titles_from_data=False)
    chart.set_categories(categories)
    chart_sheet.add_chart(chart, anchor)


def add_excel_balance_sheet_chart(workbook):
    """Add an Excel bar chart for assets and liabilities."""
    metrics_sheet = workbook["metrics"]
    chart_sheet = workbook["excel_charts"]

    metric_rows = []
    for row_number in range(2, metrics_sheet.max_row + 1):
        metric_name = metrics_sheet.cell(row=row_number, column=1).value
        if metric_name in ["Total Assets", "Total Liabilities"]:
            metric_rows.append(row_number)

    if len(metric_rows) < 2:
        return

    chart = BarChart()
    chart.title = "Assets vs Liabilities"
    chart.y_axis.title = "Amount"
    chart.x_axis.title = "Reporting Period"

    data = Reference(
        metrics_sheet,
        min_col=1,
        max_col=metrics_sheet.max_column,
        min_row=min(metric_rows),
        max_row=max(metric_rows),
    )
    categories = Reference(
        metrics_sheet,
        min_col=2,
        max_col=metrics_sheet.max_column,
        min_row=1,
        max_row=1,
    )

    chart.add_data(data, from_rows=True, titles_from_data=True)
    chart.set_categories(categories)
    chart_sheet.add_chart(chart, "A46")


def add_excel_charts(workbook, ticker):
    """Create a worksheet with Excel-native charts."""
    if "excel_charts" in workbook.sheetnames:
        del workbook["excel_charts"]

    chart_sheet = workbook.create_sheet("excel_charts")
    chart_sheet["A1"] = f"{ticker.upper()} Excel Charts"
    chart_sheet["A1"].font = Font(bold=True, size=16)

    add_excel_line_chart(workbook, "Revenue", f"{ticker.upper()} Revenue", "A3")
    add_excel_line_chart(workbook, "Net Income", f"{ticker.upper()} Net Income", "A18")
    add_excel_line_chart(workbook, "Profit Margin", f"{ticker.upper()} Profit Margin", "J3")
    add_excel_line_chart(workbook, "Cash From Operations", f"{ticker.upper()} Cash From Operations", "J18")
    add_excel_balance_sheet_chart(workbook)


def save_excel_workbook(
    ticker,
    statements,
    clean_statements,
    metrics_df,
    period_summary_df,
    explanations_df,
    file_map_df,
    output_folder,
):
    """Save all organized tables into one Excel workbook."""
    excel_filename = os.path.join(output_folder, f"{ticker.lower()}_financial_analysis.xlsx")

    with pd.ExcelWriter(excel_filename, engine="openpyxl") as writer:
        metrics_df.to_excel(writer, sheet_name="metrics")
        period_summary_df.to_excel(writer, sheet_name="periods", index=False)
        explanations_df.to_excel(writer, sheet_name="explanations", index=False)
        file_map_df.to_excel(writer, sheet_name="where_files_are_saved", index=False)

        for name, dataframe in clean_statements.items():
            dataframe.to_excel(writer, sheet_name=name[:31], index=False)

        for name, dataframe in statements.items():
            dataframe.to_excel(writer, sheet_name=f"raw_{name}"[:31], index=False)

    workbook = load_workbook(excel_filename)

    for worksheet in workbook.worksheets:
        format_excel_sheet(worksheet)

    add_excel_charts(workbook, ticker)
    workbook.save(excel_filename)

    print(f"\nSaved Excel workbook to: {os.path.abspath(excel_filename)}")


def save_csv_files(clean_statements, metrics_df, period_summary_df, output_folder):
    """Save CSV files as simple Excel-friendly backups."""
    metrics_filename = os.path.join(output_folder, "metrics.csv")
    periods_filename = os.path.join(output_folder, "periods.csv")

    metrics_df.to_csv(metrics_filename)
    period_summary_df.to_csv(periods_filename, index=False)
    print(f"Saved CSV file to: {os.path.abspath(metrics_filename)}")
    print(f"Saved CSV file to: {os.path.abspath(periods_filename)}")

    for name, dataframe in clean_statements.items():
        csv_filename = os.path.join(output_folder, f"{name}.csv")
        dataframe.to_csv(csv_filename, index=False)
        print(f"Saved CSV file to: {os.path.abspath(csv_filename)}")


def save_chart(series, title, y_label, filename):
    """Save one matplotlib line chart image."""
    chart_series = series.dropna()

    if chart_series.empty:
        print(f"Skipped {title} chart because no data was found.")
        return

    plt.figure(figsize=(10, 5))
    plt.plot(chart_series.index, chart_series.values, marker="o")
    plt.title(title)
    plt.xlabel("Reporting Period")
    plt.ylabel(y_label)
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()

    print(f"Saved chart image to: {os.path.abspath(filename)}")


def create_matplotlib_charts(ticker, metrics_df, output_folder):
    """Create chart image files with matplotlib."""
    chart_folder = os.path.join(output_folder, "charts")

    if "Revenue" in metrics_df.index:
        save_chart(metrics_df.loc["Revenue"], f"{ticker.upper()} Revenue", "Revenue", os.path.join(chart_folder, "revenue.png"))

    if "Net Income" in metrics_df.index:
        save_chart(metrics_df.loc["Net Income"], f"{ticker.upper()} Net Income", "Net Income", os.path.join(chart_folder, "net_income.png"))

    if "Profit Margin" in metrics_df.index:
        save_chart(metrics_df.loc["Profit Margin"], f"{ticker.upper()} Profit Margin", "Profit Margin (%)", os.path.join(chart_folder, "profit_margin.png"))

    if "Cash From Operations" in metrics_df.index:
        save_chart(metrics_df.loc["Cash From Operations"], f"{ticker.upper()} Cash From Operations", "Cash From Operations", os.path.join(chart_folder, "cash_from_operations.png"))

    if "Total Assets" in metrics_df.index and "Total Liabilities" in metrics_df.index:
        balance_sheet_metrics = metrics_df.loc[["Total Assets", "Total Liabilities"]].T
        balance_sheet_metrics = balance_sheet_metrics.dropna(how="all")

        plt.figure(figsize=(10, 5))
        balance_sheet_metrics.plot(kind="bar", ax=plt.gca())
        plt.title(f"{ticker.upper()} Assets vs Liabilities")
        plt.xlabel("Reporting Period")
        plt.ylabel("Amount")
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        filename = os.path.join(chart_folder, "assets_vs_liabilities.png")
        plt.savefig(filename)
        plt.close()
        print(f"Saved chart image to: {os.path.abspath(filename)}")


def main():
    """Run the financial analysis program."""
    make_output_easy_to_read()

    print("\nFinancial Analysis Tool")
    print(f"Running file: {os.path.abspath(__file__)}")

    number_of_periods = ask_for_number_of_periods()
    ticker = input("\nEnter a ticker symbol, like AAPL or MSFT: ").strip().upper()

    setup_edgar_identity()

    try:
        statements = get_financial_statement_data(ticker)
    except Exception as error:
        print("\nThe program could not pull data from the SEC/EdgarTools.")
        print("Check that you are connected to the internet and that your ticker is valid.")
        print("If this keeps happening, try again later because the SEC site may be busy.")
        print(f"\nTechnical error: {error}")
        sys.exit(1)

    output_folder = create_company_output_folder(ticker)

    period_summary_df = build_period_summary_table(statements, number_of_periods)
    explanations_df = build_explanations_table()
    file_map_df = build_file_map_table(ticker, output_folder)

    print("\n--- Reporting Periods ---")
    print(period_summary_df.to_string(index=False))
    explain_period_limits(period_summary_df)

    clean_statements = {}
    for name, dataframe in statements.items():
        clean_statements[name] = clean_statement_for_excel(dataframe, number_of_periods)
        print_clean_preview(name, clean_statements[name])

    metrics_df = build_metrics_table(statements, number_of_periods)

    print("\n--- Metrics Table ---")
    print(metrics_df.to_string())

    save_csv_files(clean_statements, metrics_df, period_summary_df, output_folder)
    save_excel_workbook(
        ticker,
        statements,
        clean_statements,
        metrics_df,
        period_summary_df,
        explanations_df,
        file_map_df,
        output_folder,
    )
    create_matplotlib_charts(ticker, metrics_df, output_folder)

    print("\nDone.")
    print(f"Open this folder to find everything: {os.path.abspath(output_folder)}")


if __name__ == "__main__":
    main()
